### ISSUE TITLE
Enhancement: Writing OLE files

### ISSUE THREAD

**Issue by jablo** [libyal/libolecf#6]
Awesome library

Are you planning to add the capability to create and write OLE files?

**Comment by joachimmetz** [comment]
Not short term. I have thought about this e.g. for building test files as a possible long term feature but this near the bottom of my current to do list.

**Comment by jablo** [comment]
I need write, and your library seems very complete. So I'm trying to decide between fixing the bugs in POLE (https://bitbucket.org/dimin/pole) which fails on my test case when writing a file larger than 22730*512 bytes.

I found your library when searching for alternative solutions. It would be somewhat cumbersome to adapt my code to using your library, but might have been worth it had you already implemented writes. For now I'll give the bug-hunting a go on POLE.

**Comment by joachimmetz** [comment]
Write support is not going to be in scope of this project anywhere soon, closing issue.
