### ISSUE TITLE
Denial of Service issue in olecinfo with fuzzed input file

### ISSUE THREAD

**Issue by fgeek** [libyal/libolecf#8]
http://bugs.fi/media/afl/libolecf/libolecf-olecinfo-dos-ae1443fb8de322b403e53776669c9cefb63ba6b0.db

```
./20170825/bin/olecfinfo libolecf-olecinfo-dos-ae1443fb8de322b403e53776669c9cefb63ba6b0.db
```
More information about the issue type: https://cwe.mitre.org/data/definitions/400.html

**Comment by joachimmetz** [comment]
thx for the report I'll have look when time permits.

**Comment by fgeek** [comment]
Thanks. Feel free to ask if you need more information. I'm fuzzing all of the tools. So far no crashes etc.

**Comment by joachimmetz** [comment]
ack, some of the libaries have been fuzzed previously with afl.

If you have tips / ideas for:
* fuzzing with specific regions of large files e.g. vshadow
* fuzzing only code paths that have changed, so I could add fuzzing to the CI tests
* corpus of test files that can be shared

let me know

**Comment by joachimmetz** [comment]
project now uses ossfuzz, closing issue
